# basic options
title: AtsutoB's Blog
author: AtsutoB
email: your-email@domain.com
description: Building data driven intelligence
twitter_username: jekyllrb
github_username:  AtsutoB

# Build settings
markdown: kramdown
theme: minima
