# basic options
title: AtsutoB's Blog
author: Building data driven intelligence
email: your-email@domain.com
description: 
twitter_username: atsutobriggs
github_username:  AtsutoB

# Build settings
markdown: kramdown
theme: minima
