# basic options
title: AtsutoB's Blog
author: Data driven project management
email: your-email@domain.com
description: 
twitter_username: atsutobriggs
github_username:  AtsutoB

# Build settings
markdown: kramdown
theme: minima
